apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name1 }}
  namespace: {{ .Values.service.namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule1 }}
  suspend: {{ .Values.cronjob.suspend1 }}
  successfulJobsHistoryLimit: 1  # Only keep the last 1 successful job
  failedJobsHistoryLimit: 1      # Only keep the last 1 failed job
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.cronjob.name1 }}
              image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
              command: 
                {{- toYaml .Values.cronjob.cmd1 | nindent 14 }}
              envFrom:
                - configMapRef:
                    name: {{ .Values.name }}
              volumeMounts:
                - name: db-certs
                  mountPath: /app/certs
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: db-certs
              secret:
                secretName: db-certs
                defaultMode: 400